sudo: false
language: rust
cache: cargo

rust:
  - stable
  - nightly
  - beta

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
script:
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo build --verbose --all
  - cargo test --verbose --all